####################################
# Port & Project Name
####################################
server:
  port: 8080                    # ?? ??
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: SBB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  ####################################
  # MySQL ??
  ####################################
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/b_ban
    username: root
    password: 1111

  ####################################
  # JPA ??
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ?????? ?????? ??
    show-sql: true          # SQL ?? ??
    properties:
      hibernate:
        format_sql: true    # SQL ??? ??

  security:
    user:
      name: test
      password: 1111
      roles: USER

####################################
# Logging 설정
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace